{{- if .Values.iva.ingress.enabled -}}
{{- $fullName := .Values.iva.name -}}
{{- $svcPort := .Values.iva.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.iva.name }}
  labels:
    app: {{ $fullName }}
  {{- with .Values.iva.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.iva.ingress.tls }}
  tls:
  {{- range .Values.iva.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.iva.ingress.host | quote }}
      http:
        paths:
        {{- range .Values.iva.ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
    - http:
        paths:
        {{- range .Values.iva.ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
{{- end }}