apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.iva.name }}
  labels:
    app: {{  .Values.iva.name  }}
spec:
  type: {{ .Values.iva.service.type }}
  ports:
    - port: {{ .Values.iva.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{  .Values.iva.name  }}