version: '3'
services:
  opencga-app:
    image: opencga-app
    ports:
     - "8080:8080"
    environment: 
      - HD_INSIGHTS_SSH_DNS=opencga-dev-ssh.azurehdinsight.net
      - HD_INSIGHTS_SSH_USER=sshuser
      - HD_INSIGHTS_SSH_PASS=${PASSWORD}
  opencga-daemon:
    image: opencga-daemon
    environment: 
      - HD_INSIGHTS_SSH_DNS=opencga-dev-ssh.azurehdinsight.net
      - HD_INSIGHTS_SSH_USER=sshuser
      - HD_INSIGHTS_SSH_PASS=${PASSWORD}
  mongo:
    image: 'mongo:3.6'
    ports:
      - '27017:27017'
    volumes:
      - 'data:/data/db'
  solr:
    image: solr:latest
    ports:
      - '8983:8983'
    #volumes:
    #  - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - opencga
volumes:
  data:
  