#cloud-config
package_upgrade: true
package_reboot_if_required: true
runcmd:
- apt-get update
- curl -fsSL https://get.docker.com/ | sh
- curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
- python3 /opt/mount.py ${mount_args}
- docker run -d -p 8080:8080 -p 8443:8443 --restart=always --mount type=bind,src=/media/primarynfs/conf,dst=/opt/opencga/conf,readonly --mount type=bind,src=/media/primarynfs/sessions,dst=/opt/opencga/sessions ${opencga_image}
- docker run -d -p 80:80 -p 443:443 --restart=always --mount type=bind,src=/media/primarynfs/conf,dst=/opt/opencga/conf,readonly --mount type=bind,src=/media/primarynfs/sessions,dst=/opt/opencga/sessions ${iva_image}

write_files:
 -  encoding: gzip
    content: !!binary |
        ${mount_script}
    path: /opt/mount.py
    permissions: \"0744\"
 -  encoding: gzip
    content: !!binary |
        ${cloud_init_check_script}
    path: /opt/cloudinitcheck.sh
    permissions: \"0744\"

