#cloud-config
package_upgrade: true
package_reboot_if_required: true

packages:
- docker.io

write_files:
- path: /etc/systemd/system/opencga.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=OpenCGA daemon
    Requires=docker.service
    After=docker.service
    
    [Service]
    Restart=always
    ExecStart=/usr/bin/docker run --name=opencga-daemon -e HD_INSIGHTS_SSH_DNS=${HD_INSIGHTS_SSH_DNS} -e HD_INSIGHTS_SSH_USER={HD_INSIGHTS_SSH_USER} -e HD_INSIGHTS_SSH_PASS=${HD_INSIGHTS_SSH_PASS} marrobi/opencga-daemon
    ExecStop=/usr/bin/docker stop opencga-daemon

