---
logLevel: "info"
logFile: ""

## CellBase client configuration, this is used mainly when annotating variants
## This can be set up using maven profiles in your .m2/settings.xml
cellbase:
  hosts:      ## 'remote' URL hosts to annotate variants, for example: http://bioinfo.hpc.cam.ac.uk/cellbase/
  - "${OPENCGA.CELLBASE.REST.HOST}"
  version: "${OPENCGA.CELLBASE.VERSION}"
  database:   ## 'local' connection to CellBase MongoDB
    hosts:
    - "${OPENCGA.CELLBASE.DB.HOST}"
    user: "${OPENCGA.CELLBASE.DB.USER}"
    password: "${OPENCGA.CELLBASE.DB.PASSWORD}"
    options:         ## This is intended for database specific options such as --authenticationDatabase in MongoDB
      authenticationDatabase: "${OPENCGA.CELLBASE.DB.AUTHENTICATION_DATABASE}"
      readPreference: "${OPENCGA.CELLBASE.DB.READ_PREFERENCE}"
      enableSSL: false

  preferred: "remote"   ## This accept two values: 'local' and 'remote' to fetch data

## Storage Query Server configuration. When CLI is launched in 'server' mode a RESTful web server
## is launched in the specified port. Only authorized hosts are allowed to query data.
server:
  rest: 9090
  grpc: 9091
  authManager: "org.opencb.opencga.storage.server.common.DefaultAuthManager"       ## Path to the AuthManager implementation class
  storageEngine: "mongodb"
  authorizedHosts: ["0.0.0.0"]
  options: {}

## Cache Configuration
cache:
  host: ${OPENCGA.STORAGE.CACHE.HOST}
  active: true
  serialization: "json"
  slowThreshold: 50
  allowedTypes: "aln,var"
  maxResultSize: 5000
  password: ""

## Solr Search Configuration
search:
  # List of hosts pointing either to the Solr nodes directly using a complete URL or to the zookeper nodes with HOST:PORT
  #    Example for Solr connection:       http://opencga-solr-01.zone:8983/solr
  #    Example for Zookeeper connection:  opencga-zookeeper-01:2181               <-- Recommended for replicated installations
  hosts:
  - ${OPENCGA.STORAGE.SEARCH.HOST}
  mode: "cloud"
  user: ""
  password: ""
  timeout: ${OPENCGA.STORAGE.SEARCH.TIMEOUT}
  insertBatchSize: 10000

## Clinical database for indexing the pathogenic variants reported.
clinical:
  # List of hosts pointing either to the Solr nodes directly using a complete URL or to the zookeper nodes with HOST:PORT
  #    Example for Solr connection:       http://opencga-solr-01.zone:8983/solr
  #    Example for Zookeeper connection:  opencga-zookeeper-01:2181               <-- Recommended for replicated installations
  hosts:
  - ${OPENCGA.STORAGE.CLINICAL.HOST}    # URL containing host and port, e.g. http://localhost:8983/solr/
  mode: "cloud"
  user: ""
  password: ""
  manager: ${OPENCGA.STORAGE.CLINICAL.MANAGER}
  timeout: ${OPENCGA.STORAGE.CLINICAL.TIMEOUT}
  insertBatchSize: 1000

benchmark:
  numRepetitions: 20
  databaseName: "opencga"
  concurrency: 5
  delay: 100
  connectionType: REST
  mode: FIXED
  rest: "http://localhost:8080/${opencga.war.name}"
  database:   ## 'local' connection to CellBase MongoDB
      hosts:
      - "localhost:27017"
      user: ""
      password: ""
      options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB

io:
  connectors:
#    azure:
#      class: "org.opencb.opencga.storage.core.io.managers.AzureBlobStorageIOConnector"
#      options:
#        accountName: "<accountName>"
#        accountKey: "<accountKey>"

alignment:
  options:
    tools.samtools: "${OPENCGA.INSTALLATION.DIR}/tools/samtools/samtools"
    transform.region_size: 200000
    transform.coverage_chunk_size: 1000
    mean_coverage_size_list: [200, 10000]

variant:
  defaultEngine: "${OPENCGA.STORAGE.DEFAULT_ENGINE}"
  options:
    species: ${OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME}
    assembly: ${OPENCGA.CLIENT.ORGANISM.ASSEMBLY}

    transform.batch.size: 200
    transform.threads: 4
    transform.format: "avro"
    transform.compression: "gzip"
    transform.fail.on.malformed: false

    load.batch.size: 100
    load.threads: 6
    stats.default-genotype: "0/0"   # Default genotype to be used for calculating stats.
    stats.multiallelic: false       # Include secondary alternates in the variant stats calculation

    query.max_timeout: 30000     #(ms) Max allowed timeout for DBAdaptor operations.
    query.default_timeout: 10000 #(ms) Default timeout for DBAdaptor operations. Only used if none is provided.
    query.limit.default: 1000              # Default limit in GET operations. To be used only if not defined.
    query.limit.max: 5000                  # Maximum limit value in GET operations. If tried to be exceeded, the query will fail.
    query.sample.limit.default: 100        # Default sampleLimit in GET operations. To be used only if not defined.
    query.sample.limit.max: 1000           # Maximum sampleLimit value in GET operations. If tried to be exceeded, the query will fail.

    search.intersect.active: true           # Allow intersect queries with the SearchEngine (Solr)
    search.intersect.always: false          # Force intersect queries
    search.intersect.params.threshold: 3    # Minimum number of QueryParams in the query to intersect

    annotation.batch.size: 100
    annotation.threads: 8
    annotation.file.format: "json"
    annotator: "cellbase"
    annotator.cellbase.exclude: "expression"
    annotator.cellbase.use_cache: true
    annotator.cellbase.imprecise_variants: true # Imprecise variants supported by cellbase (REST only)

  ## The following section defines all available storage engine plugins installed
  engines:
    ## MongoDB Storage Engine
    - id: "mongodb"
      engine: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine"
      database:
        hosts:
          - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
        user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
        password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
        options:    ## This is intended for database specific options such as --authenticationDatabase in MongoDB
          authenticationDatabase: ${OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE}
          connectionsPerHost: ${OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST}
          readPreference: "secondaryPreferred"
      options:
        mongodb.parallel.write: false
        mongodb.stage.parallel.write: false
        mongodb.direct_load.parallel.write: false
        mongodb.merge.parallel.write: false
        mongodb.merge.batch.size: 10 #Number of files to merge directly from first to second collection

    ## Hadoop Storage Engine
    - id: "hadoop"
      engine: "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine"
      database:
        hosts:
          - "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.HOSTS}"
        user: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER}"
        password: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD}"
      options:
        #Generic options

        #Plugin specific options
        dbadaptor.phoenix.fetch_size: -1
        opencga.storage.hadoop.jar-with-dependencies: "opencga-storage-hadoop-core-${opencga.version}-jar-with-dependencies.jar"
        opencga.archive.chunk_size: 1000
        hadoop.load.archive.batch.size: 3
        hadoop.load.variant.batch.size: 500
        opencga.archive.table.presplit.size: 500
        opencga.archive.table.compression: "gz"           # Allowed values: none, snappy, gz
        opencga.variant.table.presplit.size: 500
        opencga.variant.table.compression: "snappy"       # Allowed values: none, snappy, gz
        opencga.sample-index.table.presplit.size: 15
        opencga.sample-index.table.compression: "snappy"  # Allowed values: none, snappy, gz
        opencga.storage.hadoop.variant.hbase.namespace: "${OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE}"

        # Hadoop executable file. Used to lunch MapReduce applications
        opencga.hadoop.bin: "hadoop"

        # Define the way of executing MapReduce jobs.
        opencga.mr.executor: "system"  # Use system hadoop installation

        # Use external hadoop installation. ssh to a host edge node
        # opencga.mr.executor: "ssh"                 # Uncomment to enable
        opencga.mr.executor.ssh.host: ""             # Hadoop edge node host name
        opencga.mr.executor.ssh.user: ""             # Hadoop edge node user name
        # opencga.mr.executor.ssh.key: "~/.ssh/id_rsa" # Hadoop edge node ssh-key file
        opencga.mr.executor.ssh.password: ""         # Hadoop edge node password. Only if ssh-key is not present. Requires sshpass to run
        opencga.mr.executor.ssh.remote_opencga_home:  # Remote opencga home location. Only if different than local location.

        ### hadoop properties
        mapreduce.map.cpu.vcores: 1
        mapreduce.map.memory.mb: 2560
        opencga.variant.table.mapreduce.map.java.opts: -Xmx2048m,-XX:+UseG1GC,-Djava.util.concurrent.ForkJoinPool.common.parallelism=1
        opencga.storage.hadoop.hbase.merge.archive.scan.batchsize: 2000
        # Increase the ScannerTimeoutPeriod from 60000 (1min) to 300000 (5min) to avoid ScannerTimeoutExceptions
        # See opencb/opencga#352 for more info.
        opencga.storage.hadoop.mapreduce.scanner.timeout: 300000
        # 900000 -> 15 minutes
        #      hbase.client.scanner.timeout.period: 900000
        #      hbase.rpc.timeout: 900000
        ###
        #Hadoop options
        #fs.defaultFS: "${OPENCGA.STORAGE.HADOOP.HDFS.DEFAULT_FS}"
