apiVersion: v1
kind: Service
metadata:
  name: opencga-service
  labels:
    app: opencga
spec:
  type : LoadBalancer
  ports:
  - port: 8080
    targetPort : 9090
    protocol: TCP
  selector:
    app: opencga
