---
configuration:
  url: opencgaUrl
  studies:
    - id: study1
      index: true
      urlBase: fileDirUrl
      active: true
users:
  - id: demo
    password: demo
    projects:
        - id: project1
          organism:
            scientificName: hsapiens
            assembly: GRCh38
          studies:
              - id: study1
